[package]
name = "msq"
version = "0.1.0"
license = "MIT"
authors = ["mtcw99 <15316579+mtcw99@users.noreply.github.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
byteorder = "1"

